apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: retainiq-decisioning
  namespace: retainiq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: retainiq-decisioning
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: http_server_requests_per_second
        target:
          type: AverageValue
          averageValue: "800"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
