apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retainiq
  namespace: retainiq
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/rate-limit-burst: "5000"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.retainiq.com
      secretName: retainiq-tls
  rules:
    - host: api.retainiq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retainiq-decisioning
                port:
                  name: http
