apiVersion: v1
kind: Service
metadata:
  name: retainiq-decisioning
  namespace: retainiq
  labels:
    app: retainiq
    component: decisioning
spec:
  type: ClusterIP
  selector:
    app: retainiq
    component: decisioning
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
